### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by SaundersEddie** [SaundersEddie/Happenings#90]
Error executing npm run start. This is inside the server/controllers/reviewsController.js file line 2.

`[1] > happenings-app@1.1.0 start D:\UNC_Project3\happenings\client
[1] > react-scripts start
[1]
[0] We are in server user.js
[0] Inside our userController
[0] internal/modules/cjs/loader.js:796
[0]     throw err;
[0]     ^
[0]
[0] Error: Cannot find module 'mongojs'
[0] Require stack:
[0] - D:\UNC_Project3\happenings\server\controllers\reviewsController.js
[0] - D:\UNC_Project3\happenings\server\routes\api\reviews.js
[0] - D:\UNC_Project3\happenings\server\routes\api\index.js
[0] - D:\UNC_Project3\happenings\server\routes\index.js
[0] - D:\UNC_Project3\happenings\server\server.js
[0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
[0]     at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
[0]     at Object.<anonymous> (D:\UNC_Project3\happenings\server\controllers\reviewsController.js:2:17)
[0]     at Module._compile (internal/modules/cjs/loader.js:955:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
[0]     at Module.load (internal/modules/cjs/loader.js:811:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
[0]     at Module.require (internal/modules/cjs/loader.js:848:19)
[0]     at require (internal/modules/cjs/helpers.js:74:18)
[0]     at Object.<anonymous> (D:\UNC_Project3\happenings\server\routes\api\reviews.js:2:27)
[0]     at Module._compile (internal/modules/cjs/loader.js:955:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
[0]     at Module.load (internal/modules/cjs/loader.js:811:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:723:14) {
[0]   code: 'MODULE_NOT_FOUND',
[0]   requireStack: [
[0]     'D:\\UNC_Project3\\happenings\\server\\controllers\\reviewsController.js',
[0]     'D:\\UNC_Project3\\happenings\\server\\routes\\api\\reviews.js',
[0]     'D:\\UNC_Project3\\happenings\\server\\routes\\api\\index.js',
[0]     'D:\\UNC_Project3\\happenings\\server\\routes\\index.js',
[0]     'D:\\UNC_Project3\\happenings\\server\\server.js'
[0]   ]
[0] }`

**Comment by SaundersEddie** [comment]
Commenting out line 2 allows the creation of user accounts, but will error out on adding comments to code.

**Comment by SaundersEddie** [comment]
mongojs package needs to be added, will create the dependencies reference this afternon.

**Comment by SaundersEddie** [comment]
mergejs added to package.json, code the utilized it is no longer in use....
